### ISSUE TITLE
[Question] CurseForge

### ISSUE THREAD

**Issue by Saphrym** [defeatedcrow/AppleMilkTea2_1.7.10#29]
I'm being asked to make sure the mods I'm using in the modpack I am developing with PurpleMentat's minions are available on Curse Forge. Is it possible for you to add this mod to Curse Forge?

http://minecraft.curseforge.com/

I love your mod and would love to be able to include it in the modpack.

**Comment by defeatedcrow** [comment]
There is no problem that your published Mod pack contains my Mod. In addition, of course no problem that your mod pack is published in Curse Forge.
However, I'll do not move activity base of this mod to Curse Forge. I'm sorry.

Download site of this MOD is limited to my Wiki and Japan informal forum. I Since it is difficult to work in English speaking, it is difficult to appropriately manage the issue or report in multiple locations. Also, I do not want that my Mod is managed by others.

**Comment by Saphrym** [comment]
Ok. Thank you for your time. :)
