### ISSUE TITLE
Potion Extension dependency change

### ISSUE THREAD

**Issue by Adaptivity** [defeatedcrow/AppleMilkTea2_1.7.10#52]
@defeatedcrow can you add a check if mod [Extended Potions](http://minecraft.curseforge.com/mc-mods/229978-extended-potions) present? If so, AppleMilkTea shouldn't download PotionExtension because Extended Potions doing the same thing but it extends ids to 4096.

**Comment by defeatedcrow** [comment]
Potion Extension, That is not being requested only for the Potion ID. Because it contains some Fix for AMT2, it is still required to AMT2. (It was part of AMT2 in 1.6.X, and in 1.7.X it became independent.)

If you wish, I'll add a setting to stop the automatic download of Potion Extension. (It will be included to AppleMilkCore.cfg.) However, if you do it, the correct operation of AMT2 can not be guaranteed, sorry.

**Comment by Adaptivity** [comment]
Ok. I will be grateful for config option. Can you explain in two words what fix it contains? Thanks in advance.

**Comment by defeatedcrow** [comment]
- Potion Extension remove null potion effect if entity get it. That was added for removing some mod that include new potion effect, or changing config of potion ID. 
- And, sometimes potion ID is expanded by several other mods, and sometimes it becomes the more than 128. That will be cause a crush. Potion Extension fix that crush when potion ID is 256 or less.

These functions, may be able to also resolved by Extended Potion. In that case, when even if you stop the automatic download of Potion Extension, AMT2 works.

**Comment by Adaptivity** [comment]
Thanks for info. I don't know if Extended Potions can remove null potion effect but it allows to set potion id higher than 128 (Potion id limit with Extended Potions is 4096). So, config option would be cool :smile:

**Comment by Adaptivity** [comment]
Thanks for a change.
