### ISSUE TITLE
add 1.12.2 and higher versions

### ISSUE THREAD

**Issue by leonpano2006** [defeatedcrow/AppleMilkTea2_1.7.10#73]
this mod alreadey long time no update
please update this very good mod

**Comment by defeatedcrow** [comment]
The main elements of this mod are included in [HeatAndClimate](https://github.com/defeatedcrow/HeatAndClimateMod) and are still being updated.
Therefore, there will be no updates as AMT in the future.

**Comment by leonpano2006** [comment]
> The main elements of this mod are included in [HeatAndClimate](https://github.com/defeatedcrow/HeatAndClimateMod) and are still being updated.
> 
> Therefore, there will be no updates as AMT in the future.

Please documented this into readme and on curseforge

**Comment by defeatedcrow** [comment]
There are no plans to support AMT. Since AMT has completely stopped and the development environment is also broken, I'll not be doing any updates to announce. Especially for curseforge, I'm not an AMT page owner, so I don't care about page management.

Many users are already following HaC, and HaC's ReadMe and other info have announced that HaC includes some AMT remade.
We don't put a lot of effort into publicity, so announcements may be lacking. Basic information is published on my personal site (https://defeatedcrow.jp/modwiki/Mainpage) and ReadMe for each mod.
